version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=lnichols
      - POSTGRES_PASSWORD=lnichols
      - POSTGRES_DB_NAME=lnichols